# Generated by Django 4.0.1 on 2022-02-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_quotemodel_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotemodel',
            name='tel',
            field=models.CharField(max_length=30, verbose_name='tel'),
        ),
    ]
