# Generated by Django 4.0.1 on 2022-03-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_drivers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='previus_employer',
            field=models.IntegerField(verbose_name='driver license'),
        ),
    ]
