# Generated by Django 4.0.1 on 2022-06-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_drivers_previus_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='driver_license',
            field=models.CharField(max_length=50, verbose_name='driver license'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='phone number'),
        ),
    ]
